### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gahr** [nsd20463/pwsafe#1]
Hi Nicolas, great to see you got back to maintain pwsafe! Are you planning a new release anytime soon? I'd like to see the couple of bugs you fixed make their ways into a fetchable tarball and be able to update the FreeBSD port. Thanks!

**Comment by graysky2** [comment]
Also glad to see activity.  Great lightweight util.

**Comment by nsd20463** [comment]
I think 0.2.1 should be soon, just as a bug and build fix on the very old 0.2.0.
I have some more patches people have emailed me or left on sourceforge over the years to merge in first, as well as looking at what the people who forked pwsafe on their own have done (there are 2 I know of here on github)
Anyway this is open source. You don't need me to make yourself your own release :-)

**Comment by gahr** [comment]
Sounds great, thanks a lot!

**Comment by nsd20463** [comment]
glad it worked out for you
