### ISSUE TITLE
Build failure: dependency on X11/Xmu

### ISSUE THREAD

**Issue by dolmen** [nsd20463/pwsafe#11]
Building from master (9d9758fa540ab673376dc855d331aaf80192c6c6), `configure` detects that X11/Xmu/Atoms.h is missing, but continues. However the build then fails because this file is missing.

If the XMU library is necessary for building the configure script should fail if it detects it is missing.
If the XMU library is not necessary, `pwsafe.cpp` should have conditionals blocks based on `HAVE_LIBXMU` from `config.h`.

Details below.

Extract of the configure output when building on Ubuntu 16.04 (without packages `libxmu-dev`, `libxmu-headers`):

```
checking X11/Xlib.h usability... yes
checking X11/Xlib.h presence... yes
checking for X11/Xlib.h... yes
checking X11/Xatom.h usability... yes
checking X11/Xatom.h presence... yes
checking for X11/Xatom.h... yes
checking X11/Xmu/Atoms.h usability... no
checking X11/Xmu/Atoms.h presence... no
checking for X11/Xmu/Atoms.h... no
```

But the build fails:

```
LC_MESSAGES=C make
make  all-am
make[1]: Entering directory '/home/omengue/tmp/pwsafe'
g++ -DHAVE_CONFIG_H -I.     -g -O2 -Wall -MT pwsafe.o -MD -MP -MF .deps/pwsafe.Tpo -c -o pwsafe.o pwsafe.cpp
pwsafe.cpp:120:27: fatal error: X11/Xmu/Atoms.h: No such file or directory
compilation terminated.
Makefile:636: recipe for target 'pwsafe.o' failed
make[1]: *** [pwsafe.o] Error 1
make[1]: Leaving directory '/home/omengue/tmp/pwsafe'
Makefile:522: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by faxm0dem** [comment]
same here.
I disabled the X11 code using `--without-x` as I only need the cli

**Comment by nsd20463** [comment]
libxmu headers are required of X11 is used. configure.ac has been updated to reflect that.
