### ISSUE TITLE
feature request: paste twice

### ISSUE THREAD

**Issue by helbling** [nsd20463/pwsafe#14]
Chromium needs the same paste filled twice.
See these Bugs:
https://bugs.chromium.org/p/chromium/issues/detail?id=819113
https://bugs.chromium.org/p/chromium/issues/detail?id=778686

I'd suggest a workaround: `pwsafe -t -up foobar` fills username and password twice.

**Comment by progo** [comment]
Can confirm this new `-t` switch helps with Vivaldi. Doesn't help with Firefox 59 or Google Chrome binary. Do you have per chance any idea what could be different in Firefox and Chromium approaches?

**Comment by helbling** [comment]
No. Only whats written here:
https://bugs.chromium.org/p/chromium/issues/detail?id=778686#c2
I suppose Chromium chose option 1 and Firefox option 2.

**Comment by progo** [comment]
That's unfortunate, but thanks.

**Comment by chmeee** [comment]
In Chrome, I use -up to paste only the password. It's a quick and dirty trick.
I like the -t option as a way to overcome this situation.
I wonder if there's any reason why the PR hasn't been merged yet.

**Comment by michaelkuhn** [comment]
As a note for others encountering the problem: You can use Ctrl+Shift+V in Chrome to make it read the clipboard only once.

**Comment by nsd20463** [comment]
-t/--twice option merged (finally)
