### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by Hawk777** [nsd20463/pwsafe#16]
Hi! I’m not sure if there is a better way to contact you than this. Your website [here](http://nsd.dyndns.org/pwsafe/) seems to be offline. This is relevant to pwsafe because that website used to carry the 0.2.0 release, which, I *think*, was the most recent, and does not seem to be present here on Github.

**Comment by mauro3** [comment]
There is an archived version here:
https://web.archive.org/web/20190116040527/http://nsd.dyndns.org/pwsafe/

**Comment by nsd20463** [comment]
The entire dyndns.org was sold, resold, and eventually owned by a certain Mr Larry Ellison of Oracle fame.
They ruined it, and that killed nsd.dyndns.org as a viable domain name.
I have not replaced it, mostly out of lazyness.

0.2.0 is pretty old. I suggest building from the source here on github. I'll try and do a github-based release, but I'll have to read the docs first.

**Comment by hippi777** [comment]
hi there! :)

i just came here to suggest to use https://www.nsupdate.info

i couldnt find anything better than this back in time when i did my research on the available ddns services, however it was a few years ago, but at least this didnt become any worse as far as i can tell

bests! :)
